# Generated by Django 4.0 on 2021-12-20 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='comments',
            field=models.ManyToManyField(blank=True, to='courses.Comment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_section',
            field=models.ManyToManyField(blank=True, to='courses.CourseSection'),
        ),
        migrations.AlterField(
            model_name='section',
            name='episodes',
            field=models.ManyToManyField(blank=True, to='courses.Episode'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='related_courses',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
